name: kalorat
description: "Kalorat - Calorie Tracker & Meal Logger"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # Camera & Media
  camera: ^0.11.0+2
  image_picker: ^1.1.2

  # Networking
  http: ^1.2.2
  connectivity_plus: ^7.0.0
  url_launcher: ^6.2.5

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.4

  # State Management
  provider: ^6.1.2

  # Charts
  fl_chart: ^1.1.1

  # Localization
  intl: any

  # Onboarding
  introduction_screen: ^4.0.0

  # File Operations
  file_picker: ^10.3.10

  # Notifications
  flutter_local_notifications: ^20.0.0
  timezone: ^0.10.0

  # Permissions
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - lib/assets/

flutter_launcher_icons:
  android: true
  ios: true
  theme_color: "#0F5838" 
  image_path: "lib/assets/kalorat-favicon-ios.png"
  adaptive_icon_background: "#F7F5F2"
  adaptive_icon_foreground: "lib/assets/kalorat-favicon-android.png"
  remove_alpha_ios: true 
  background_color_ios: "#F7F5F2"
